[master] Version: 2.0.0 - "Format: <type>(<scope>): <description>"

diff --git a/lib/templates/prepare-commit-msg/prepare-commit-msg-version b/lib/templates/prepare-commit-msg/prepare-commit-msg-version
--- a/lib/templates/prepare-commit-msg/prepare-commit-msg-version
+++ b/lib/templates/prepare-commit-msg/prepare-commit-msg-version
@@ -1,17 +1,21 @@
 #!/bin/sh
-
-echo "🔖 Adding Version Info to Commit Message..."
-
+# will be applicable when adding commit using `git commit`
+echo -e "\033[33m🔖 Adding Version Info to Commit Message...\033[0m"
 # Check if package.json exists
 if [ ! -f "package.json" ]; then
-  echo "❌ package.json not found! Ensure your project has a package.json."
+  echo -e "\033[31;1m❌ package.json not found! Ensure your project has a package.json.\033[0m"
   exit 1
 fi
 
-# Extract version from package.json
-version=$(jq -r '.version' package.json)
+version=$(grep -o '"version": *"[^"]*"' package.json | sed -E 's/.*: *"([^"]*)"/\1/')
+
+# Validate if version was extracted
+if [ -z "$version" ]; then
+  echo -e "\033[31;1m❌ Unable to extract version from package.json.\033[0m"
+  exit 1
+fi
 
 # Append version info to commit message
 echo "Version: $version - $(cat "$1")" > "$1"
 
-echo "✅ Version info added to commit message."
+echo -e "\033[32;1m✅ Version info added to commit message.\033[0m"
